name: build-and-upload

on:
  push:
    branches:
      - master

jobs:
  build-and-upload:
    name: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: sudo apt-get install awscli
      - run: which aws
      - run: ./upload.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
        if: ${{ failure() }}
        with:
          limit-access-to-actor: true
