name: build-and-upload

on:
  push:
    branches:
      - master

jobs:
  build-and-upload:
    name: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - run: sudo apt-get update && sudo apt-get install awscli
      - run: ./upload.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
