name: build-and-upload

on:
  push:
    branches:
      - master

jobs:
  build-and-upload:
    name: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: chrislennon/action-aws-cli@v1.1
      - run: npm install
      - run: ./upload.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
